[package]
name = "subs2srs-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.1"
rfd = "0.15.4"
srtparse = "0.2.0"
tokio = { version = "1.47.1", features = ["full"] }

[dev-dependencies]
uuid = { version = "1.8.0", features = ["v4"] }
